---
# tasks file for wiki
  - name: add gpg
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: add repo
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

  - name: install docker
    ansible.builtin.apt:
      update_cache: true
      name: docker-ce
      state: present

  - name: copy
    ansible.builtin.copy:
      src: "./wiki/files/wiki.yml"
      dest: "/tmp/wiki.yml"

